
version: '3.8'
services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management-alpine
    # environment:
    #   RABBITMQ_DEFAULT_USER: user
    #   RABBITMQ_DEFAULT_PASS: user
    ports:
      # Expose ports for RabbitMQ
      - 5672:5672
      # Expose ports for RabbitMQ web interface
      - 15672:15672
  loginapi:
    container_name: loginapi
    image: loginapi
    networks:
      - app-network
    environment:
      - secretPath=/run/secrets/jwtSecret
      - ConnectionStrings__DockerLoginDB=Host=postgres-container;Port=5432;Database=LoginAPI;Username=postgres;Password=postgres
    secrets:
      - jwtSecret
    build:
       context: LoginApi
       dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "10001:8080"
      - "10002:8081"
    volumes:
      - C:/Users/45527/Documents/Keys:/home/app/.aspnet/DataProtection-Keys
      - C:/Users/45527/Documents/cert.pem:/app/cert.pem
  
  postgres:
    container_name: postgres-container
    image: postgres:latest
    networks:
      - app-network
    environment:
      postgres_db: loginapi
      postgres_user: postgres
      postgres_password: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./.containers/users-db:/var/lib/postgresql/data

  gameserverapi:
    container_name: game_server_api
    image: game_server_api
    networks:
      - app-network
    environment:
     - secretPath=/run/secrets/jwtSecret 
    secrets:
     - jwtSecret
    build:
      context: GameServerAPI
      dockerfile: Dockerfile
    ports:
      - "10003:8080"
      - "10004:8081"
    volumes:
      - C:/Users/45527/Documents/Keys:/home/app/.aspnet/DataProtection-Keys
      - C:/Users/45527/Documents/cert.pem:/app/cert.pem

  chatapi:
    container_name: chatapi
    image: chatapi
    networks:
      - app-network
    environment:
      - secretPath=/run/secrets/jwtSecret
    secrets:
      - jwtSecret
    build:
      context: ChatApi
      dockerfile: Dockerfile
    ports:
      - "10005:8080"
      - "10006:8081"
    volumes:
      - C:/Users/45527/Documents/Keys:/home/app/.aspnet/DataProtection-Keys
      - C:/Users/45527/Documents/cert.pem:/app/cert.pem


networks:
  app-network:

volumes:
  postgres_data:
     name: custom_postgres_data
  
secrets:
  jwtSecret:
    file: ./mysecret.txt


